#ifndef CODIGOS_OPERACION_H_
#define CODIGOS_OPERACION_H_

typedef enum
{
	MENSAJE_DE_KERNEL,
	MENSAJE_DE_MEMORIA,
	MENSAJE_DE_FILESYSTEM,
	MENSAJE_DE_CPU_INTERRUPT,
	MENSAJE_DE_CPU_DISPATCH,
	MENSAJE_DE_CPU,
	HANDSHAKE_CPU_MEMORIA,
	INICIAR_PROCESO
} op_code;

#endif /* CODIGOS_OPERACION_H_ */
