#ifndef CONSTANTES_H_
#define CONSTANTES_H_

// Otros
#define EOF_FS UINT32_MAX

// Nombres de instrucciones
#define SET_NOMBRE_INSTRUCCION "SET"
#define SUM_NOMBRE_INSTRUCCION "SUM"
#define SUB_NOMBRE_INSTRUCCION "SUB"
#define JNZ_NOMBRE_INSTRUCCION "JNZ"
#define SLEEP_NOMBRE_INSTRUCCION "SLEEP"
#define WAIT_NOMBRE_INSTRUCCION "WAIT"
#define SIGNAL_NOMBRE_INSTRUCCION "SIGNAL"
#define MOV_IN_NOMBRE_INSTRUCCION "MOV_IN"
#define MOV_OUT_NOMBRE_INSTRUCCION "MOV_OUT"
#define FOPEN_NOMBRE_INSTRUCCION "F_OPEN"
#define FCLOSE_NOMBRE_INSTRUCCION "F_CLOSE"
#define FSEEK_NOMBRE_INSTRUCCION "F_SEEK"
#define FREAD_NOMBRE_INSTRUCCION "F_READ"
#define FWRITE_NOMBRE_INSTRUCCION "F_WRITE"
#define FTRUNCATE_NOMBRE_INSTRUCCION "F_TRUNCATE"
#define EXIT_NOMBRE_INSTRUCCION "EXIT"

// Nombres de registros
#define AX_NOMBRE_REGISTRO "AX"
#define BX_NOMBRE_REGISTRO "BX"
#define CX_NOMBRE_REGISTRO "CX"
#define DX_NOMBRE_REGISTRO "DX"
#define PC_NOMBRE_REGISTRO "PC"

// Nombres de modulos
#define NOMBRE_MODULO_KERNEL "Kernel"
#define NOMBRE_MODULO_CPU "CPU"
#define NOMBRE_MODULO_CPU_INTERRUPT "CPU (INTERRUPT)"
#define NOMBRE_MODULO_CPU_DISPATCH "CPU (DISPATCH)"
#define NOMBRE_MODULO_FILESYSTEM "Filesystem"
#define NOMBRE_MODULO_MEMORIA "Memoria"

// Estado procesos (codigos)
#define CODIGO_ESTADO_PROCESO_NEW 'N'
#define CODIGO_ESTADO_PROCESO_READY 'R'
#define CODIGO_ESTADO_PROCESO_EXECUTING 'X'
#define CODIGO_ESTADO_PROCESO_EXIT 'E'
#define CODIGO_ESTADO_PROCESO_BLOCKED 'B'

// Estado procesos (nombres completos)
#define NOMBRE_ESTADO_PROCESO_NEW "NEW"
#define NOMBRE_ESTADO_PROCESO_READY "READY"
#define NOMBRE_ESTADO_PROCESO_EXECUTING "EXEC"
#define NOMBRE_ESTADO_PROCESO_EXIT "EXIT"
#define NOMBRE_ESTADO_PROCESO_BLOCKED "BLOCKED"

// Algoritmos de planificacion
#define ALGORITMO_PLANIFICACION_FIFO "FIFO"
#define ALGORITMO_PLANIFICACION_ROUND_ROBIN "RR"
#define ALGORITMO_PLANIFICACION_PRIORIDADES "PRIORIDADES"

// Motivo de interrupcion
#define INTERRUPCION_POR_DESALOJO 1
#define INTERRUPCION_POR_KILL 2

// Motivo de finalizacion
#define FINALIZACION_SUCCESS 1
#define FINALIZACION_INVALID_RESOURCE 2
#define FINALIZACION_INVALID_WRITE 3

// Operacion archivo
#define ABRIR_ARCHIVO 1
#define CREAR_ARCHIVO 2
#define TRUNCAR_ARCHIVO 3
#define LEER_ARCHIVO 4
#define ESCRIBIR_ARCHIVO 5

// Modo apertura / Locks
#define LOCK_LECTURA 1
#define LOCK_ESCRITURA 2

#endif /* CONSTANTES_H_ */