#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum
{
	MENSAJE_DE_KERNEL,
	MENSAJE_DE_MEMORIA,
	MENSAJE_DE_FILESYSTEM,
	MENSAJE_DE_CPU_INTERRUPT,
	MENSAJE_DE_CPU_DISPATCH,
	MENSAJE_DE_CPU,
	
	EJECUTAR_PROCESO,
	INTERRUMPIR_PROCESO,
	DEVOLVER_PROCESO_POR_SER_INTERRUMPIDO,
	DEVOLVER_PROCESO_POR_CORRECTA_FINALIZACION,
	SOLICITAR_INFO_DE_MEMORIA_INICIAL_PARA_CPU,
	ENVIAR_INFO_DE_MEMORIA_INICIAL_PARA_CPU,
	INICIAR_PROCESO_MEMORIA,
	ESTADO_INICIAR_PROCESO_MEMORIA,
	ENVIAR_INSTRUCCION_MEMORIA_A_CPU,
	SOLICITAR_INSTRUCCION_A_MEMORIA,
	FINALIZAR_PROCESO_MEMORIA,
	LEER_ARCHIVO_MEMORIA,
	ESCRIBIR_ARCHIVO_MEMORIA,
	PEDIR_BLOQUES_A_FILESYSTEM,
	LIBERAR_BLOQUES_EN_FILESYSTEM
} op_code;

const char* nombre_opcode(op_code opcode);

#endif /* ENUMS_H_ */
