#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum
{	
	// Kernel a CPU
	SOLICITUD_EJECUTAR_PROCESO,
	SOLICITUD_INTERRUMPIR_PROCESO,
	RESPUESTA_DEVOLVER_PROCESO_POR_SER_INTERRUMPIDO,
	RESPUESTA_DEVOLVER_PROCESO_POR_CORRECTA_FINALIZACION,
	RESPUESTA_DEVOLVER_PROCESO_POR_SLEEP,
	
	// Kernel a Memoria
	SOLICITUD_INICIAR_PROCESO_MEMORIA,
	SOLICITUD_FINALIZAR_PROCESO_MEMORIA,
	
	// CPU a Kernel
	RESPUESTA_EJECUTAR_PROCESO,
	RESPUESTA_INTERRUMPIR_PROCESO,
	SOLICITUD_DEVOLVER_PROCESO_POR_SER_INTERRUMPIDO,
	SOLICITUD_DEVOLVER_PROCESO_POR_CORRECTA_FINALIZACION,
	SOLICITUD_DEVOLVER_PROCESO_POR_SLEEP,

	// CPU a Memoria
	SOLICITUD_PEDIR_INSTRUCCION_A_MEMORIA,
	SOLICITUD_PEDIR_INFO_DE_MEMORIA_INICIAL_PARA_CPU,

	// Memoria a Kernel
	RESPUESTA_INICIAR_PROCESO_MEMORIA,
	RESPUESTA_FINALIZAR_PROCESO_MEMORIA,
	
	// Memoria a CPU
	RESPUESTA_PEDIR_INSTRUCCION_A_MEMORIA,
	RESPUESTA_PEDIR_INFO_DE_MEMORIA_INICIAL_PARA_CPU,

	// Memoria a Filesystem
	SOLICITUD_PEDIR_BLOQUES_A_FILESYSTEM,
	SOLICITUD_LIBERAR_BLOQUES_EN_FILESYSTEM,
	SOLICITUD_CONTENIDO_BLOQUE_EN_FILESYSTEM,
	SOLICITUD_ESCRIBIR_PAGINA_EN_SWAP,
	RESPUESTA_LEER_ARCHIVO_MEMORIA,
	RESPUESTA_ESCRIBIR_ARCHIVO_MEMORIA,
	RESPUESTA_LEER_VALOR_EN_MEMORIA_DESDE_FILESYSTEM,

	// Filesystem a Memoria
	SOLICITUD_LEER_ARCHIVO_MEMORIA,
	SOLICITUD_ESCRIBIR_ARCHIVO_MEMORIA,
	SOLICITUD_LEER_VALOR_EN_MEMORIA_DESDE_FILESYSTEM,
	RESPUESTA_PEDIR_BLOQUES_A_FILESYSTEM,
	RESPUESTA_CONTENIDO_BLOQUE_EN_FILESYSTEM,
	RESPUESTA_LIBERAR_BLOQUES_EN_FILESYSTEM,

	//Kernel a FileSystem
	SOLICITUD_ABRIR_ARCHIVO_FS,
	SOLICITUD_CREAR_ARCHIVO_FS,
	SOLICITUD_TRUNCAR_ARCHIVO_FS,
	SOLICITUD_LEER_ARCHIVO_FS,
	SOLICITUD_ESCRIBIR_ARCHIVO_FS,




	// FS a Kernel
	OK,

	// DEFECTO
	OPCODE_DEFECTO
} op_code;

const char* nombre_opcode(op_code opcode);

#endif /* ENUMS_H_ */
