#ifndef NOMBRES_MODULOS_H_
#define NOMBRES_MODULOS_H_

#define NOMBRE_MODULO_KERNEL "Kernel"
#define NOMBRE_MODULO_CPU "CPU"
#define NOMBRE_MODULO_CPU_INTERRUPT "CPU (INTERRUPT)"
#define NOMBRE_MODULO_CPU_DISPATCH "CPU (DISPATCH)"
#define NOMBRE_MODULO_FILESYSTEM "Filesystem"
#define NOMBRE_MODULO_MEMORIA "Memoria"

#endif /* NOMBRES_MODULOS_H_ */